### ISSUE TITLE
ICA problem

### ISSUE THREAD

**Issue by Ainavo** [ZitongLu1996/Python-EEG-Handbook#3]
您好，请问mne中会有像eeglab中对伪迹成分的一个相似度的判别吗？还是mne中只能通过人工确定哪些成分属于伪迹？期待您的回复。

**Comment by ZitongLu1996** [comment]
目前没有，不过MNE官网提供了一些去ICA的方法，可以参考：https://mne.tools/stable/auto_tutorials/preprocessing/40_artifact_correction_ica.html

**Comment by Ainavo** [comment]
好的，非常感谢
